### PR TITLE
Reconnect on abnormal websocket errors

### PR DESCRIPTION
**Pull request by MattDavies**
Getting some issues where the websocket connection is terminated abnormally after a period of time, just sharing the code I used to reconnect in those scenarios (it won't reconnect on a normal close which is socket code 1000).

### CODE REVIEW

**Comment by escwdev** [comment]
Generally, I prefer to leave the connection handling to end users. As long as the error produces a return value of some kind that can be handled, I'd rather have the user determine whether to reconnect automatically or follow some other code path.

I'm going to leave this here now and I'll consider it as I review and implement some other changes.

**Comment by MattDavies** [comment]
Sure. For me this was triggering a code 1006 which doesn't call the error handler (some kind of lower level error).

**Comment by escwdev** [comment]
Are you able to handle it how you want to without having to adjust this libs code?

**Comment by MattDavies** [comment]
Unfortunately not as that particular 1006 error code / scenario doesn't seem to trigger the error handler, but I can just maintain a fork or if you like I can adjust the reconnect to be configurable.

**Pull request closed without merging**
